// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0QM9amS-XC-DTeNvwRq-jdXpFwHn2nsc',
    appId: '1:1042375285915:web:e9912fc20bbca42c88fa3e',
    messagingSenderId: '1042375285915',
    projectId: 'auctora-cbf7c',
    authDomain: 'auctora-cbf7c.firebaseapp.com',
    storageBucket: 'auctora-cbf7c.firebasestorage.app',
    measurementId: 'G-Q188818MM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZl4B3AbZB-NNEDMBzbZnbT7tLGQLyt3w',
    appId: '1:1042375285915:android:4ef399eb0bce088388fa3e',
    messagingSenderId: '1042375285915',
    projectId: 'auctora-cbf7c',
    storageBucket: 'auctora-cbf7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmQTEjXumPOXGYVc4SKf9dbkPaW8CqNp4',
    appId: '1:1042375285915:ios:c3632fa1214b426b88fa3e',
    messagingSenderId: '1042375285915',
    projectId: 'auctora-cbf7c',
    storageBucket: 'auctora-cbf7c.firebasestorage.app',
    iosBundleId: 'com.example.auctora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmQTEjXumPOXGYVc4SKf9dbkPaW8CqNp4',
    appId: '1:1042375285915:ios:c3632fa1214b426b88fa3e',
    messagingSenderId: '1042375285915',
    projectId: 'auctora-cbf7c',
    storageBucket: 'auctora-cbf7c.firebasestorage.app',
    iosBundleId: 'com.example.auctora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0QM9amS-XC-DTeNvwRq-jdXpFwHn2nsc',
    appId: '1:1042375285915:web:a5a1794ce94e432888fa3e',
    messagingSenderId: '1042375285915',
    projectId: 'auctora-cbf7c',
    authDomain: 'auctora-cbf7c.firebaseapp.com',
    storageBucket: 'auctora-cbf7c.firebasestorage.app',
    measurementId: 'G-8Z0972YPVD',
  );
}
